### ISSUE TITLE
Ansible get_url task Failed to validate sha256 checksum using URL in release 1.12

### ISSUE THREAD

**Issue by emmanuelgirard** [F5Networks/f5-telemetry-streaming#72]
### Environment
 * Telemetry Streaming Version: 1.12.0-3
 * BIG-IP Version: 15.1.0.4-0.0.6

### Summary
The sha256 checksum format of the file is not valid, it should not include the "dist/" folder before the file name.

### Steps To Reproduce
1. Submit the following declaration:
```yml
---
- name: Download telemetry package
  hosts: localhost

  tasks:

  - name: Download TS package v1.11 with remote checksum url (worked)
    get_url:
      url: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.11.0/f5-telemetry-1.11.0-1.noarch.rpm"
      dest: "rpms"
      checksum: "sha256:https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.11.0/f5-telemetry-1.11.0-1.noarch.rpm.sha256"

  - name: Download TS package v1.12 with remote checksum url (failed)
    get_url:
      url: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.12.0/f5-telemetry-1.12.0-3.noarch.rpm"
      dest: "rpms"
      checksum: "sha256:https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.12.0/f5-telemetry-1.12.0-3.noarch.rpm.sha256"
```

2. Observe the following error response:
```bash
PLAY [Download telemetry package] ****************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************
ok: [localhost]

TASK [Download TS package v1.11 with remote checksum url (worked)] *******************************************************************
changed: [localhost]

TASK [Download TS package v1.12 with remote checksum url (failed)] *******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find a checksum for file 'f5-telemetry-1.12.0-3.noarch.rpm' in 'https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.12.0/f5-telemetry-1.12.0-3.noarch.rpm.sha256'"}

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

### Expected Behavior
Like release 1.11, remote url for checksum should work.

### Actual Behavior
Checksum file format include path and break Ansible Task
